# Generated by Django 4.1.7 on 2023-03-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('kms_driven', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('engine_vol', models.IntegerField()),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
